import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, Download, Maximize2, X, Image as ImageIcon } from 'lucide-react';
import { SlidesWidgetData } from '../types';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import PptxGenJS from 'pptxgenjs';

interface SlidesWidgetProps {
  data: SlidesWidgetData;
}

export const SlidesWidget: React.FC<SlidesWidgetProps> = ({ data }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % data.slides.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + data.slides.length) % data.slides.length);
  };

  const downloadPresentation = () => {
    const pres = new PptxGenJS();
    pres.layout = 'LAYOUT_16x9';

    // Theme Colors
    const BG_COLOR = '18181b';
    const TEXT_COLOR = 'f4f4f5';
    const ACCENT_COLOR = '20b8cd';

    // Title Slide
    let slide = pres.addSlide();
    slide.background = { color: BG_COLOR }; 
    slide.addText(data.title, { 
        x: 0.5, y: 2.5, w: '90%', h: 1.5, 
        fontSize: 44, color: ACCENT_COLOR, bold: true, align: 'center', fontFace: 'Arial' 
    });
    slide.addText('Generated by Impersio', { 
        x: 0.5, y: 4.2, w: '90%', h: 0.5, 
        fontSize: 14, color: '71717a', align: 'center', fontFace: 'Arial' 
    });

    // Content Slides
    data.slides.forEach((s) => {
        slide = pres.addSlide();
        slide.background = { color: BG_COLOR };
        
        // Slide Title
        slide.addText(s.title, { 
            x: 0.5, y: 0.4, w: '90%', h: 0.6, 
            fontSize: 28, color: ACCENT_COLOR, bold: true, fontFace: 'Arial' 
        });

        // Determine Layout based on content
        const hasChart = !!s.chart;
        const hasImage = !!s.image;
        
        let textWidth = '90%';
        let textY = 1.2;

        if (hasChart || hasImage) {
            textWidth = '50%';
        }

        // Bullet Points
        const bullets = s.content.map(text => ({ 
            text, 
            options: { 
                fontSize: 16, 
                color: TEXT_COLOR, 
                breakLine: true, 
                bullet: { type: 'bullet', code: '2022' }, 
                paraSpaceBefore: 10 
            } 
        }));
        
        slide.addText(bullets, { 
            x: 0.5, y: textY, w: textWidth, h: 5, 
            align: 'left', valign: 'top', fontFace: 'Arial' 
        });

        // Add Chart
        if (hasChart && s.chart) {
             const chartData = [
                {
                    name: s.chart.title || "Data",
                    labels: s.chart.data.map(d => d.label),
                    values: s.chart.data.map(d => d.value)
                }
             ];
             slide.addChart(pres.ChartType.bar, chartData, { 
                 x: 5.5, y: 1.5, w: 4.5, h: 3.5, 
                 chartColors: [ACCENT_COLOR],
                 valAxisLabelColor: '71717a',
                 catAxisLabelColor: '71717a',
                 valAxisLineColor: '333333',
                 catAxisLineColor: '333333'
             });
        }

        // Add Image
        if (hasImage && s.image && !hasChart) {
            try {
                slide.addImage({ 
                    path: s.image, 
                    x: 5.5, y: 1.5, w: 4.5, h: 3.5,
                    sizing: { type: 'contain', w: 4.5, h: 3.5 }
                });
            } catch (e) {
                console.error("Failed to add image to PPT", e);
            }
        }
    });

    pres.writeFile({ fileName: `${data.title.replace(/[^a-zA-Z0-9]/g, '_')}.pptx` });
  };

  const currentSlide = data.slides[currentIndex];

  const RenderContent = () => (
    // Changed: Removed animate-fade-in to prevent jumping. Added fade-in for opacity only.
    <div key={currentIndex} className="absolute inset-0 p-8 flex flex-col animate-in fade-in duration-300">
        <h2 className="text-2xl md:text-3xl font-bold text-scira-accent mb-6 leading-tight truncate">
            {currentSlide.title}
        </h2>
        
        <div className="flex-1 flex gap-6 min-h-0">
            {/* Text Content */}
            <div className={`flex-1 overflow-y-auto ${currentSlide.chart || currentSlide.image ? 'w-1/2' : 'w-full'}`}>
                <ul className="space-y-4">
                    {currentSlide.content.map((point, idx) => (
                        <li key={idx} className="flex items-start gap-3 text-lg text-primary/90">
                            <span className="mt-2.5 w-1.5 h-1.5 rounded-full bg-scira-accent shrink-0" />
                            <span className="leading-relaxed">{point}</span>
                        </li>
                    ))}
                </ul>
            </div>

            {/* Right Side: Chart or Image */}
            {(currentSlide.chart || currentSlide.image) && (
                <div className="w-1/2 h-full flex items-center justify-center">
                    {currentSlide.chart ? (
                        <div className="w-full h-full max-h-[300px] bg-background/50 rounded-xl p-4 border border-border">
                            <h3 className="text-sm font-semibold text-muted mb-4 uppercase tracking-wider">{currentSlide.chart.title || "Data Analysis"}</h3>
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={currentSlide.chart.data}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                                    <XAxis 
                                        dataKey="label" 
                                        stroke="#71717a" 
                                        tick={{fill: '#71717a', fontSize: 12}} 
                                        tickLine={false} 
                                        axisLine={false}
                                        interval={0}
                                    />
                                    <YAxis 
                                        stroke="#71717a" 
                                        tick={{fill: '#71717a', fontSize: 12}} 
                                        tickLine={false} 
                                        axisLine={false} 
                                    />
                                    <Tooltip 
                                        contentStyle={{backgroundColor: '#18181b', borderColor: '#27272a', color: '#fff'}}
                                        itemStyle={{color: '#fff'}}
                                        cursor={{fill: '#27272a', opacity: 0.5}}
                                    />
                                    <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                                        {currentSlide.chart.data.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={index % 2 === 0 ? '#20b8cd' : '#3f2510'} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    ) : currentSlide.image ? (
                        <div className="w-full h-full max-h-[300px] rounded-xl overflow-hidden border border-border relative">
                            <img 
                                src={currentSlide.image} 
                                alt={currentSlide.title} 
                                className="w-full h-full object-cover"
                            />
                        </div>
                    ) : null}
                </div>
            )}
        </div>
    </div>
  );

  if (isFullscreen) {
    return (
        <div className="fixed inset-0 z-50 bg-background flex flex-col p-6 animate-in zoom-in-95 duration-200">
             <div className="absolute top-4 right-4 flex gap-4 z-10">
                 <button onClick={downloadPresentation} className="p-2 rounded-full bg-surface hover:bg-surface-hover text-primary transition-colors flex items-center gap-2 px-4">
                     <Download className="w-5 h-5" />
                     <span className="text-sm font-medium">Download PPTX</span>
                 </button>
                 <button onClick={() => setIsFullscreen(false)} className="p-2 rounded-full bg-surface hover:bg-surface-hover text-primary transition-colors">
                     <X className="w-5 h-5" />
                 </button>
             </div>
             
             <div className="flex-1 flex items-center justify-center max-w-7xl mx-auto w-full">
                 <div className="w-full aspect-[16/9] bg-surface border border-border rounded-2xl relative shadow-2xl overflow-hidden">
                    <RenderContent />
                    
                     {/* Controls */}
                    <div className="absolute inset-x-0 top-1/2 -translate-y-1/2 flex justify-between px-4 pointer-events-none">
                        <button onClick={prevSlide} className="pointer-events-auto p-4 rounded-full bg-black/50 hover:bg-black/70 text-white backdrop-blur-sm transition-all hover:scale-105 active:scale-95">
                            <ChevronLeft className="w-8 h-8" />
                        </button>
                        <button onClick={nextSlide} className="pointer-events-auto p-4 rounded-full bg-black/50 hover:bg-black/70 text-white backdrop-blur-sm transition-all hover:scale-105 active:scale-95">
                            <ChevronRight className="w-8 h-8" />
                        </button>
                    </div>
                    
                    <div className="absolute bottom-6 right-8 text-sm text-muted font-medium bg-background/90 px-3 py-1 rounded-full border border-border">
                        {currentIndex + 1} / {data.slides.length}
                    </div>
                 </div>
             </div>
        </div>
    );
  }

  return (
    <div className="w-full max-w-3xl mx-auto mb-8 bg-surface border border-border rounded-2xl overflow-hidden shadow-lg transition-all hover:shadow-xl group">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-surface-hover/30">
         <div className="flex items-center gap-2">
             <div className="w-3 h-3 rounded-full bg-red-500/80" />
             <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
             <div className="w-3 h-3 rounded-full bg-green-500/80" />
         </div>
         <div className="text-xs font-semibold text-muted uppercase tracking-wider truncate max-w-[200px]">{data.title}</div>
         <div className="flex items-center gap-1">
             <button onClick={downloadPresentation} className="p-1.5 rounded-lg text-muted hover:text-primary hover:bg-background/50 transition-colors" title="Download PPTX">
                 <Download className="w-4 h-4" />
             </button>
             <button onClick={() => setIsFullscreen(true)} className="p-1.5 rounded-lg text-muted hover:text-primary hover:bg-background/50 transition-colors" title="Fullscreen">
                 <Maximize2 className="w-4 h-4" />
             </button>
         </div>
      </div>

      {/* Slide Preview */}
      <div className="aspect-[16/9] bg-background relative overflow-hidden group/preview">
          <RenderContent />
          
          {/* Controls Overlay */}
          <div className="absolute inset-0 flex items-center justify-between px-2 opacity-0 group-hover/preview:opacity-100 transition-opacity pointer-events-none">
              <button onClick={prevSlide} className="pointer-events-auto p-2 rounded-full bg-black/20 hover:bg-black/40 text-white backdrop-blur-sm transition-all hover:scale-110">
                  <ChevronLeft className="w-5 h-5" />
              </button>
              <button onClick={nextSlide} className="pointer-events-auto p-2 rounded-full bg-black/20 hover:bg-black/40 text-white backdrop-blur-sm transition-all hover:scale-110">
                  <ChevronRight className="w-5 h-5" />
              </button>
          </div>
          
          <div className="absolute bottom-3 right-4 text-[10px] text-muted font-medium bg-background/80 px-2 py-0.5 rounded-full border border-border">
              {currentIndex + 1} / {data.slides.length}
          </div>
      </div>
    </div>
  );
};